config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'beers#index'

    resources :beers

end

app/models/beer.rb
class Beer < ActiveRecord::Base
	mount_uploader :img, ImgUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController

  # before_action :authorize

    def index
      @beers = Beer.all.order(created_at: :desc)
      # if current_user
        # @beers = current_user.beers.all.order(created_at: :desc)
        # @beers = current_user.beers.all.order(created_at: :desc).paginate(:page => params[:page], :per_page => 6)
      # end
    end

    def new
      @beer = Beer.new
    end

    def create
      # @beer = current_user.beers.new(beer_params)
      @beer = Beer.new(beer_params)
      if @beer.save
        redirect_to beers_path
      else
        flash[:danger] = "Entry needs a name"
        redirect_to new_beer_path
      end
    end

    def show
      # @beer = current_user.beers.find(params[:id])
      @beer = Beer.find(params[:id])
    end

    def edit
      # @beer = current_user.beers.find(params[:id]) 
      @beer = Beer.find(params[:id])   
    end

    def update
      # @beer = current_user.beers.find(params[:id])
      @beer = Beer.find(params[:id])
      if @beer.update(beer_params)
      redirect_to beers_path
      else
      render :edit
      end
    end

    def destroy
      # @beer = current_user.beers.find(params[:id])
      @beer = Beer.find(params[:id])
      @beer.destroy
      redirect_to beers_path
    end

    def beer_params
      params.require(:beer).permit(:name, :brewery, :style, :alc, :price, :rating, :img, :color)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/beers/_landing.html.erb
<!-- Nav -->

<div class="nav">
	<% if user_signed_in? %>
	Logged in as <strong><%= current_user.email %></strong>.
		<%= link_to 'Edit profile', edit_user_registration_path %> |
		<%= link_to "Logout", destroy_user_session_path, method: :delete %>
	<% else %>
		<%= link_to "login", new_user_session_path %>
	<% end %>
</div>

<!-- Secton 1 -->

<div class="hero">
	<div>
		<img src="<%= asset_path('logo.svg') %>" >
		<h1> a simple app.<br>with a complex obsession.</h1>
		<h2> kanpai <span>for beer drinkers</span></h2>
	</div>
</div>

<div class="about">
	<div>
		<h1>welcome to kanpai.beer</h1>
		<h2><span>kanpai.beer</span> is a simple app for beer drinkers & craft beer enthusiats.</h2>
		<h2>Stripped clean of all the trappings of social media,<br><span>kanpai.beer</span> lets you focus on the finer aspects of being a beer conniseur.</h2>
		<h2>Keep track of beers you want to drink with the wishlist.<br>Once you’ve polished off that frosty mug, create a concise review.</h2>
		<h2>Best of all, <span>it’s free to use!</span></h2>
		<button><%= link_to "try it now", new_user_registration_path %></button>
	</div>
</div>

<div class="how">
		<div class="how-inner">
			<div class="how-text-a">
				<h1>the proper way to kanpai</h1>
			</div>
			<div class="mugs">
				<img src="<%= asset_path('mug.svg') %>" >
				<img src="<%= asset_path('mug.svg') %>" >
			</div>
			<div class="arrows">
				<div class="arrow-left">
					<div class="line"></div>
					<div class="line"></div>
					<div class="line"></div>
				</div>
				<h1><span>!</span></h1>
				<div class="arrow">
					<div class="line"></div>
					<div class="line"></div>
					<div class="line"></div>
				</div>
			</div>
			<h1 id="cheers"><span>kanpai!</span></h1>
			<div class="how-text-b">
				<h2>while looking your drinking mate in the eye,<br>bring your glasses together and shout “kanpai!”</h2>
				<p>* resize the window for a demonstration</p>
			</div>
		</div>
</div>

<div class="footer">
	
</div>

app/views/beers/edit.htlm.erb
		<%= form_for @beer do |f| %>
			<div class="b3"><%= @beer.name.upcase %></div>
			<br/>
			<div class="l1">
				Brewery:<br/> 
				<%= f.text_field :brewery, placeholder: "Brewery", size: "25px" %><br/>
				Style:<br/>
				<%= f.text_field :style, placeholder: "Style", size: "25px" %><br/>
				ABV:<br/> 
				<%= f.number_field :ABV, placeholder: "ABV", size: "25px" %><br/>
				Rating:<br/> 
				<%= f.number_field :rating, placeholder: "(1-10)", size: "25px" %><br/>
				Price:<br/> 
				<%= f.number_field :price, placeholder: "Price", size: "25px" %><br/>
				Taste:<br/> 
				<%= f.text_field :taste, list: "tastes", placeholder: "flavor", size: "25px" %><br/>
				<datalist id=tastes>
						<option>Dry</option>
						<option>Hoppy</option>
						<option>Sour</option>
						<option>Sweet</option>
						<option>Crisp</option>
					</datalist>
				<br/>Color:
				<%= f.color_field :color, list: "colors", placeholder: "#ffeaa5" %><br/>
				<br/>Label Photo:<br/>  
				<%= f.file_field :photo %></div><br/>
				<div><%= f.submit "Update", class: "l1"%></div>
					<datalist id=colors>
						<option>#ffeaa5</option>
						<option>#efc784</option>
						<option>#f5b65d</option>
						<option>#e69943</option>
						<option>#d28d44</option>
						<option>#ce6f2b</option>
						<option>#ce4c36</option>
						<option>#653615</option>
						<option>#5f332a</option>
						<option>#261408</option>
					</datalist>
				<% end %>

app/views/beers/edit.html.erb
		<%= form_for @beer do |f| %>
			<div class="b3"><%= @beer.name.upcase %></div>
			<br/>
			<div class="l1">
				Brewery:<br/> 
				<%= f.text_field :brewery, placeholder: "Brewery", size: "25px" %><br/>
				Style:<br/>
				<%= f.text_field :style, placeholder: "Style", size: "25px" %><br/>
				ABV:<br/> 
				<%= f.number_field :alc, placeholder: "ABV", size: "25px" %><br/>
				Rating:<br/> 
				<%= f.number_field :rating, placeholder: "(1-10)", size: "25px" %><br/>
				Price:<br/> 
				<%= f.number_field :price, placeholder: "Price", size: "25px" %><br/>
				<datalist id=tastes>
						<option>Dry</option>
						<option>Hoppy</option>
						<option>Sour</option>
						<option>Sweet</option>
						<option>Crisp</option>
					</datalist>
				<br/>Color:
				<%= f.color_field :color, list: "colors", placeholder: "#ffeaa5" %><br/>
				<br/>Label Photo:<br/>  
				<%= f.file_field :img %></div><br/>
				<div><%= f.submit "Update", class: "l1"%></div>
					<datalist id=colors>
						<option>#ffeaa5</option>
						<option>#efc784</option>
						<option>#f5b65d</option>
						<option>#e69943</option>
						<option>#d28d44</option>
						<option>#ce6f2b</option>
						<option>#ce4c36</option>
						<option>#653615</option>
						<option>#5f332a</option>
						<option>#261408</option>
					</datalist>
				<% end %>

app/views/beers/index.html.erb
<%= render partial: 'beers/landing'%>

<!-- Nav -->

<div class="nav">
	<% if user_signed_in? %>
	Logged in as <strong><%= current_user.email %></strong>.
		<%= link_to 'Edit profile', edit_user_registration_path %> |
		<%= link_to "Logout", destroy_user_session_path, method: :delete %>
	<% else %>
		<%= link_to "login", new_user_session_path %>
	<% end %>
</div>

<!-- content goes here -->

<div class="wishlist">
<h1>wish list</h1>
	<div class="wishlist-inner">
		<div class="wishlist-table">
			<div class="wishlist-titles">
					<h3>beer</h3>
					<h3>brewery</h3>
					<h3>style</h3>
			</div>
			<% @beers.each do |b| %>
				<div class="wishlist-item">
					<h2><%= b.name %></h2>
					<h2><%= b.brewery %></h2>
					<h2><%= b.style %></h2>
					<button>×</button>
					<button>r</button>
				</div>
			<% end %>
		</div>
	</div>
</div>

<!-- reviews -->

<div class="collection">
	<h1>collection</h1>
	<div class="collection-inner">
		<% @beers.each do |b| %>
		<div class="cover" style="background-image: url(<%= b.img %>);">
			<div>
			<h2><%= link_to b.name, beer_path(b) %></h2>
			</div>
			<!-- <img src="<%= b.img.url %>" class="cover-background">  *to use filter would have to put image in seperate div -->
		</div>
		<% end %>
	</div>
</div>

<div class="footer"></div>

app/views/beers/new.html.erb
<%= form_for @beer do |f| %>
  <div>
    Name: <%= f.text_field :name %>
    Brewery: <%= f.text_field :brewery %>
    Style: <%= f.text_field :style %>
		<span><%= f.submit "+" %></span>
  </div>
  <% end %><br/>
  <% flash.each do |key, value| %>
  	<br/><span><div class='alert-<%= key %>' role='danger'>
    	<%= value %>
  	</div></span>
	<% end %>

app/views/beers/show.html.erb
<div class="show-container">
	<h1><%= @beer.name.upcase %></h1>
	<div class="show-inner">
		<div  class="show-info">
			<h2><span>brewery:</span> <%= @beer.brewery  %></h2>
			<h2><span>style:</span> <%= @beer.style %></h2>
			<h2><span>abv% :</span> <%= @beer.alc %></h2>
			<h2><span>rating:</span> <%= @beer.rating %> out of 10</h2>
			<h2><span>price:</span> $<%= @beer.price %></h2>
			<h2><span>color:</span></h2>
			<div class="color-bar" style="color:<%= @beer.color %>"></div>
				<div class="show-buttons">
		<button><%= link_to 'REVISE', edit_beer_path(@beer) %></button><button><%= link_to "X", @beer, method: :delete, data: { confirm: "Are you sure?"} %></button><button><%= link_to "BACK", beers_path %></button>
	</div>
		</div>
			<%= image_tag @beer.img.url %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kanpai16</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>